-- DDL (Data Definition Language)

--CREATE TABLE SUPERMERCADO
CREATE TABLE IF NOT EXISTS STF_FILIAL_SUPERMERCADO (
	NRO_INT_FIL_SUP SERIAL PRIMARY KEY,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	NOME VARCHAR(100) NOT NULL,
	UF CHAR(2) NOT NULL,
	LOGRADOURO VARCHAR(45) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL,
	NUMERO INT NOT NULL,
	CEP CHAR(9) NOT NULL
);


--CREATE TABLE FUNCIONARIO
CREATE TABLE IF NOT EXISTS STF_FUNCIONARIO (
	NRO_INT_FUN SERIAL PRIMARY KEY,
	NRO_INT_FIL_SUP INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF CHAR(11) NOT NULL UNIQUE,
	CONSTRAINT FK_FUNCIONARIO_SUPERMERCADO
	FOREIGN KEY (NRO_INT_FIL_SUP)
	REFERENCES STF_FILIAL_SUPERMERCADO (NRO_INT_FIL_SUP)
	
);


--CREATE TABLE CAIXA
CREATE TABLE IF NOT EXISTS STF_CAIXA (
	NRO_INT_CAI SERIAL PRIMARY KEY,
	NRO_INT_FIL_SUP INT NOT NULL,
	TIPO_ATENDIMENTO VARCHAR(45) NOT NULL,
	CONSTRAINT FK_CAIXA_SUPERMERCADO
	FOREIGN KEY (NRO_INT_FIL_SUP) REFERENCES STF_FILIAL_SUPERMERCADO (NRO_INT_FIL_SUP)
);


--CREATE TABLE CONTROLE CAIXA
CREATE TABLE IF NOT EXISTS STF_CONTROLE_CAIXA (
	NRO_INT_CON_CAI SERIAL PRIMARY KEY,
	NRO_INT_FUN INT NOT NULL,
	NRO_INT_CAI INT NOT NULL,
	DT_ABERTURA DATE NOT NULL,
	DT_FECHAMENTO DATE NULL,
	VLR_INICIAL DECIMAL(11,2) NOT NULL,
	VLR_FINAL DECIMAL(11,2) NULL,
	CONSTRAINT FK_CONTROLE_FUNCIONARIO
	FOREIGN KEY (NRO_INT_FUN) REFERENCES STF_FUNCIONARIO (NRO_INT_FUN),
	CONSTRAINT FK_CONTROLE_CAIXA
	FOREIGN KEY (NRO_INT_CAI) REFERENCES STF_CAIXA (NRO_INT_CAI)
);


--CREATE TABLE PAGAMENTO
CREATE TABLE IF NOT EXISTS STF_PAGAMENTO(
	NRO_INT_PAG SERIAL PRIMARY KEY,
	FORMA_PAGAMENTO VARCHAR(45) NOT NULL,
	INSTITUICAO_FINANCEIRA VARCHAR(45) NOT NULL,
	BANDEIRA VARCHAR(45) NULL
);


--CREATE TABLE VENDA
CREATE TABLE IF NOT EXISTS STF_VENDA(
	NRO_INT_VEN SERIAL PRIMARY KEY,
	NRO_INT_CON_CAI INT NOT NULL,
	NRO_INT_PAG INT NOT NULL,
	DT_VENDA DATE NOT NULL,
	VLR_VENDA DECIMAL(11,2) NOT NULL,
	CONSTRAINT FK_CONTROLE_VENDA
	FOREIGN KEY (NRO_INT_CON_CAI) REFERENCES STF_CONTROLE_CAIXA (NRO_INT_CON_CAI),
	CONSTRAINT FK_PAGAMENTO_VENDA
	FOREIGN KEY (NRO_INT_PAG) REFERENCES STF_PAGAMENTO (NRO_INT_PAG)
);


--CREATE TABLE CATEGORIA PRODUTO
CREATE TABLE IF NOT EXISTS STF_CATEGORIA_PRODUTO(
	NRO_INT_CAT_PRO SERIAL PRIMARY KEY,
	CATEGORIA VARCHAR(45) NOT NULL
);


--CREATE TABLE CATALOGO
CREATE TABLE IF NOT EXISTS STF_CATALOGO(
	NRO_INT_CAT SERIAL PRIMARY KEY,
	NRO_INT_CAT_PRO INT NOT NULL,
	NOME_PRODUTO VARCHAR(100) NOT NULL,
	CODIGO_DE_BARRAS CHAR(13) NOT NULL UNIQUE,
	QTD_CONTIDA INT NOT NULL,
	IND_ISCAIXA CHAR(1) NOT NULL,
	CONSTRAINT FK_CATEGORIA_CATALOGO
	FOREIGN KEY (NRO_INT_CAT_PRO) REFERENCES STF_CATEGORIA_PRODUTO (NRO_INT_CAT_PRO)
);


--CREATE TABLE LOTE
CREATE TABLE IF NOT EXISTS STF_LOTE(
	NRO_INT_LOT SERIAL PRIMARY KEY,
	NRO_INT_CAT INT NOT NULL,
	DT_RECEBIMENTO DATE NOT NULL,
	VLR_PAGO DECIMAL(11,2) NOT NULL,
	QTD_RECEBIDA INT NOT NULL,
	NRO_LOTE CHAR(6) NOT NULL UNIQUE,
	IND_ISALOCADO CHAR(6) NOT NULL,
	DT_VALIDADE DATE NOT NULL,
	CONSTRAINT FK_PRODUTO_LOTE
	FOREIGN KEY (NRO_INT_CAT) REFERENCES STF_CATALOGO (NRO_INT_CAT)
);


--CREATE TABLE ESTOQUE
CREATE TABLE IF NOT EXISTS STF_ESTOQUE(
	NRO_INT_EST SERIAL PRIMARY KEY,
	NRO_INT_LOT INT NOT NULL,
	NRO_INT_FIL_SUP INT NOT NULL,
	NRO_INT_CAT INT NOT NULL,
	QTD_DISPONIVEL INT NOT NULL,
	CONSTRAINT FK_LOTE_ESTOQUE
	FOREIGN KEY (NRO_INT_LOT) REFERENCES STF_LOTE (NRO_INT_LOT),
	CONSTRAINT FK_SUPERMERCADO_ESTOQUE
	FOREIGN KEY (NRO_INT_FIL_SUP) REFERENCES STF_FILIAL_SUPERMERCADO (NRO_INT_FIL_SUP),
	CONSTRAINT FK_CATALOGO_ESTOQUE
	FOREIGN KEY (NRO_INT_CAT) REFERENCES STF_CATALOGO (NRO_INT_CAT)
);


--CREATE TABLE HISTORICO PRECO
CREATE TABLE IF NOT EXISTS STF_HISTORICO_PRECO(
	NRO_INT_HIS_PRE SERIAL PRIMARY KEY,
	NRO_INT_EST INT NOT NULL,
	VLR_VENDA DECIMAL(11,2) NOT NULL,
	DT_ALTERACAO DATE NOT NULL,
	HHMMSS_ALTERACAO TIME NOT NULL,
	CONSTRAINT FK_ESTOQUE_PRECO
	FOREIGN KEY (NRO_INT_EST) REFERENCES STF_ESTOQUE (NRO_INT_EST)
);


--CREATE TABLE PRODUTO VENDA
CREATE TABLE IF NOT EXISTS STF_PRODUTO_VENDA(
	NRO_INT_PRO_VEN SERIAL PRIMARY KEY,
	NRO_INT_VEN INT NOT NULL,
	NRO_INT_HIS_PRE INT NOT NULL,
	QTD_PRODUTO INT NOT NULL,
	VLR_SOMA_PRODUTO DECIMAL(11,2) NOT NULL,
	CONSTRAINT FK_VENDA_PRODUTO_VENDA
	FOREIGN KEY (NRO_INT_VEN) REFERENCES STF_VENDA (NRO_INT_VEN),
	CONSTRAINT FK_VENDA_HISTORICO
	FOREIGN KEY (NRO_INT_HIS_PRE) REFERENCES STF_HISTORICO_PRECO (NRO_INT_HIS_PRE)
);


--CREATE TABLE NOTA FISCAL
CREATE TABLE IF NOT EXISTS STF_NOTA_FISCAL(
	NRO_INT_NOT_FIS SERIAL PRIMARY KEY,
	NRO_INT_FIL_SUP INT NOT NULL,
	NRO_INT_VEN INT NOT NULL,
	DT_EMISSAO DATE NOT NULL,
	CPF_CLIENTE CHAR(11) NULL,
	CODIGO_DE_BARRAS CHAR(13) NOT NULL,
	VLR_TOTAL_COM_TRIBUTOS DECIMAL(11,2) NOT NULL,
	VLR_ICMS DECIMAL(11,2) NOT NULL,
	CONSTRAINT FK_SUPERMERCADO_NOTA_FISCAL
	FOREIGN KEY (NRO_INT_FIL_SUP) REFERENCES STF_FILIAL_SUPERMERCADO (NRO_INT_FIL_SUP),
	CONSTRAINT FK_VENDA_NOTA_FISCAL
	FOREIGN KEY (NRO_INT_VEN) REFERENCES STF_VENDA (NRO_INT_VEN)
);